@host=http://localhost:8080

GET https://api.github.com/users/algaworks/repos

###
GET {{host}}/cozinhas
Accept: application/xml

###
GET {{host}}/cozinhas/1

###
POST {{host}}/cozinhas
Content-Type: application/json

{
   "nome": "Brasileira"
}

###
PUT {{host}}/cozinhas/1
Content-Type: application/json

{
  "nome": "Mexicana"
}
