@host=http://localhost:8080

GET https://api.github.com/users/algaworks/repos

###
GET {{host}}/cozinhas
Accept: application/xml

###
GET {{host}}/cozinhas/1

###
POST {{host}}/cozinhas
Content-Type: application/json

{
   "nome": "Brasileira"
}

###
PUT {{host}}/cozinhas/1
Content-Type: application/json

{
  "nome": "Mexicana"
}

###
DELETE {{host}}/cozinhas/3

###
GET {{host}}/restaurantes

###
GET {{host}}/restaurantes/1

###
POST {{host}}/restaurantes
Content-Type: application/json

{
    "nome": "Copo imundo",
    "taxaFrete": 12,
    "cozinha": {
        "id": 1
    }
}

###
PUT {{host}}/restaurantes/4
Content-Type: application/json

{
    "nome": "Copo Imundo",
    "taxaFrete": 5,
    "cozinha": {
        "id": 2
    }
}

###
GET {{host}}/estados

###
POST {{host}}/estados
Content-Type: application/json

{
    "nome": "Rio de Janeiro"
}

###
PUT {{host}}/estados/1
Content-Type: application/json

{
    "nome": "Espirito Santo"
}

###
DELETE {{host}}/estados/2

###
GET {{host}}/cidades

###
POST {{host}}/cidades
Content-Type: application/json

{
    "nome" : "Angra dos Reis",
    "estado": {
       "id": 1
    }
}

###
PUT {{host}}/cidades/2
Content-Type: application/json

{
    "nome" : "Angra dos Reis",
    "estado": {
        "id": 2
    }
}

###
DELETE {{host}}/cidades/2
